/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemUI;

import SystemModel.DB4OUtil.DB4OUtil;
import SystemModel.EcoSystem;
import SystemModel.Enterprise.Enterprise;
import SystemModel.Network.Network;
import SystemModel.Organization.Organization;
import SystemModel.UserAccount.UserAccount;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;


/**
 *
 * @author Karan
 */
public class MainJFrame extends javax.swing.JFrame {

    
    private EcoSystem ecosystem;
    private DB4OUtil db4outil=DB4OUtil.getInstance();
   
    public MainJFrame() {
        initComponents();
        
          Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setSize(550, 350);
        
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
         ecosystem=db4outil.retrieveSystem();
        EcoSystem.setInstance(ecosystem);
        
        Time();
        Date();
    }
    
    public void Time(){
    
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            Date d= new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
            //timeLabel.setText(sdf.format(d));   
            }
        
        }
        ).start();
    }
    
    
     public void Date(){
    
    Date d= new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
//    dateLabel.setText(sdf.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        controlArea = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        passwordTxtField = new javax.swing.JPasswordField();
        workArea = new javax.swing.JPanel();
        txttitle = new javax.swing.JLabel();
        txtquote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SplitPane.setBackground(new java.awt.Color(255, 255, 255));
        SplitPane.setDividerLocation(150);
        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlArea.setBackground(new java.awt.Color(255, 102, 102));
        controlArea.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N

        lblusername.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblusername.setText("Username:");

        lblpassword.setBackground(new java.awt.Color(255, 255, 255));
        lblpassword.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblpassword.setText("Password:");

        usernameTxtField.setBackground(java.awt.Color.black);
        usernameTxtField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        usernameTxtField.setForeground(java.awt.Color.white);

        loginBtn.setBackground(java.awt.Color.gray);
        loginBtn.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(java.awt.Color.gray);
        logoutBtn.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        passwordTxtField.setBackground(java.awt.Color.black);
        passwordTxtField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        passwordTxtField.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout controlAreaLayout = new javax.swing.GroupLayout(controlArea);
        controlArea.setLayout(controlAreaLayout);
        controlAreaLayout.setHorizontalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblusername, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(63, 63, 63)
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(controlAreaLayout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usernameTxtField)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1919, Short.MAX_VALUE))
        );

        controlAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblpassword, lblusername});

        controlAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordTxtField, usernameTxtField});

        controlAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {loginBtn, logoutBtn});

        controlAreaLayout.setVerticalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameTxtField))
                .addGap(18, 18, 18)
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassword))
                .addGap(18, 18, 18)
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(logoutBtn))
                .addContainerGap())
        );

        controlAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblpassword, lblusername, passwordTxtField, usernameTxtField});

        controlAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {loginBtn, logoutBtn});

        SplitPane.setTopComponent(controlArea);

        workArea.setBackground(java.awt.Color.white);
        workArea.setLayout(new java.awt.CardLayout());

        txttitle.setFont(new java.awt.Font("Georgia", 3, 48)); // NOI18N
        txttitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txttitle.setText("Welcome to Careerspire, ");
        workArea.add(txttitle, "card2");

        txtquote.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        txtquote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtquote.setText("We solve earth scale problems in Education, Job and Entrepreneurship.");
        workArea.add(txtquote, "card3");

        SplitPane.setRightComponent(workArea);

        getContentPane().add(SplitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 776));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        
    
    String userName= usernameTxtField.getText();
   
    char[] passwordArray= passwordTxtField.getPassword();
    
    String password= String.valueOf(passwordArray);
    
    if(userName.equals("")|| password.equals("")){
    
    JOptionPane.showMessageDialog(null, " All fields are necessary ");
                return;
        
    }
    else{
 
    UserAccount useraccount=ecosystem.getUserAccountDirectory().authenticateUser(userName, password);
    
    Enterprise inEnterprise=null;
    
    Organization inOrganization=null;
    
    if(useraccount==null)
    {
     
        for(Network network:ecosystem.getNetworkList())
        {
        
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList())
            {
                
                useraccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                
                if(useraccount==null){
                   
                    for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        
                        useraccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                        
                        if(useraccount!=null)
                        {
                            
                            inEnterprise=enterprise;
                            
                            inOrganization=organization;
                            
                            break;
                        }
                    }
                }else{
                    inEnterprise=enterprise;
                    break;
                }
                if(inEnterprise!=null){
                    break;
                }
                if(inEnterprise!=null){
                    break;
                }
                        }
                    }
                }
            if(useraccount==null)
            {
                JOptionPane.showMessageDialog(null, "Incorrect Username/Password, Please try again!");
                return;
            }else
            {
                CardLayout layout=(CardLayout) workArea.getLayout();
                //AbsoluteLayout = (AbsoluteLayout) workArea.getLayout();
                
                workArea.add("workArea",useraccount.getRole().createWorkArea(workArea, useraccount, inOrganization, inEnterprise, ecosystem));
                
                layout.next(workArea);
            }
            loginBtn.setEnabled(false);
            logoutBtn.setEnabled(true);
            usernameTxtField.setEnabled(false);
            passwordTxtField.setEnabled(false);
                                           

        
    } 
    }//GEN-LAST:event_loginBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
       String userName= usernameTxtField.getText();
   
    char[] passwordArray= passwordTxtField.getPassword();
    
    String password= String.valueOf(passwordArray);
    
    if(userName.equals("")|| password.equals("")){
    
    JOptionPane.showMessageDialog(null, " Please first Login");
                return;
        
    }
    else{ 
    logoutBtn.setEnabled(false);
    loginBtn.setEnabled(true);
    usernameTxtField.setEnabled(true);
    passwordTxtField.setEnabled(true);
    
    usernameTxtField.setText("");
    passwordTxtField.setText("");
    
    workArea.removeAll();
    JPanel blankJPanel= new JPanel();
    workArea.add("blank",blankJPanel);
    CardLayout crdLyt=(CardLayout)workArea.getLayout();
    crdLyt.next(workArea);
    db4outil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutBtnActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel controlArea;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JLabel txtquote;
    private javax.swing.JLabel txttitle;
    private javax.swing.JTextField usernameTxtField;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
