/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemUI.SystemAdministrator;

import SystemModel.EcoSystem; 
import SystemModel.Enterprise.Enterprise;
import SystemModel.Network.Network;
import SystemModel.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Karan
 */
public class SystemAdministrator extends javax.swing.JPanel {

    
    private EcoSystem ecosystem;
    private JPanel workArea;
    
    
    public SystemAdministrator(EcoSystem ecosystem, JPanel workArea) {
        initComponents();
        
        this.ecosystem=ecosystem;
        this.workArea=workArea;
    }

   

   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnterpriseBtn = new javax.swing.JButton();
        manageEnterpriseAdministratorBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageNetworkBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEnterpriseBtn.setBackground(java.awt.Color.gray);
        manageEnterpriseBtn.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        manageEnterpriseBtn.setText("Manage Enterprise");
        manageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseBtnActionPerformed(evt);
            }
        });
        add(manageEnterpriseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 308, 215, 50));

        manageEnterpriseAdministratorBtn.setBackground(java.awt.Color.gray);
        manageEnterpriseAdministratorBtn.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        manageEnterpriseAdministratorBtn.setText("Manage Enterprise Administrator");
        manageEnterpriseAdministratorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdministratorBtnActionPerformed(evt);
            }
        });
        add(manageEnterpriseAdministratorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 393, -1, 50));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("System Administrator Work Area");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1025, -1));

        manageNetworkBtn.setBackground(java.awt.Color.gray);
        manageNetworkBtn.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        manageNetworkBtn.setText("Manage Network");
        manageNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkBtnActionPerformed(evt);
            }
        });
        add(manageNetworkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 223, 215, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        //        ManageEnterprise system = new ManageEnterprise(downJPanel,ecosystem);
        //        downJPanel.add("ManageEnterprise", system);
        //        CardLayout layout= (CardLayout) downJPanel.getLayout();
        //        layout.next(downJPanel);
    }//GEN-LAST:event_manageEnterpriseBtnActionPerformed

    private void manageEnterpriseAdministratorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdministratorBtnActionPerformed
        // TODO add your handling code here:
        //        ManageEnterpriseAdministrator system = new ManageEnterpriseAdministrator(downJPanel,ecosystem);
        //        downJPanel.add("ManageEnterpriseAdmin", system);
        //        CardLayout layout= (CardLayout) downJPanel.getLayout();
        //        layout.next(downJPanel);
    }//GEN-LAST:event_manageEnterpriseAdministratorBtnActionPerformed

    private void manageNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkBtnActionPerformed
        // TODO add your handling code here:
        //         ManageNetwork system = new ManageNetwork(downJPanel,ecosystem);
        //        downJPanel.add("ManageNetwork", system);
        //        CardLayout layout= (CardLayout) downJPanel.getLayout();
        //        layout.next(downJPanel);
    }//GEN-LAST:event_manageNetworkBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton manageEnterpriseAdministratorBtn;
    private javax.swing.JButton manageEnterpriseBtn;
    private javax.swing.JButton manageNetworkBtn;
    // End of variables declaration//GEN-END:variables
}
