/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemUI.SystemAdministrator;

import SystemModel.EcoSystem; 
import SystemModel.Enterprise.Enterprise;
import SystemModel.Network.Network;
import SystemModel.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Karan
 */
public class SystemAdministrator extends javax.swing.JPanel {

    
    private EcoSystem ecosystem;
    private JPanel workArea;
    
    
    public SystemAdministrator(EcoSystem ecosystem, JPanel workArea) {
        initComponents();
        this.ecosystem=ecosystem;
        this.workArea=workArea;
    }

   

   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageEnterprise = new javax.swing.JButton();
        btnManageEnterpriseAdministrator = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblSystemAdministrator = new javax.swing.JLabel();
        btnManageNetwork = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(2353, 776));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageEnterprise.setBackground(java.awt.Color.gray);
        btnManageEnterprise.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        add(btnManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 280, 50));

        btnManageEnterpriseAdministrator.setBackground(java.awt.Color.gray);
        btnManageEnterpriseAdministrator.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnManageEnterpriseAdministrator.setText("Manage Enterprise Administrator");
        btnManageEnterpriseAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseAdministratorActionPerformed(evt);
            }
        });
        add(btnManageEnterpriseAdministrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, -1, 50));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        lblSystemAdministrator.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblSystemAdministrator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSystemAdministrator.setText("System Administrator");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSystemAdministrator, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSystemAdministrator)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 80));

        btnManageNetwork.setBackground(java.awt.Color.gray);
        btnManageNetwork.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 280, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        // TODO add your handling code here:
               EnterpriseManagement system = new EnterpriseManagement(workArea,ecosystem);
               workArea.add("EnterpriseManagement", system);
               CardLayout layout= (CardLayout) workArea.getLayout();
               layout.next(workArea);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageEnterpriseAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseAdministratorActionPerformed
        // TODO add your handling code here:
               EnterpriseAdministrator system = new EnterpriseAdministrator(workArea,ecosystem);
                workArea.add("EnterpriseAdministrator", system);
                CardLayout layout= (CardLayout) workArea.getLayout();
                layout.next(workArea);
    }//GEN-LAST:event_btnManageEnterpriseAdministratorActionPerformed

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        // TODO add your handling code here:
               NetworkManagement system = new NetworkManagement(workArea,ecosystem);
               workArea.add("NetworkManagement", system);
               CardLayout layout= (CardLayout) workArea.getLayout();
               layout.next(workArea);
          
        
    }//GEN-LAST:event_btnManageNetworkActionPerformed
// public void populateTree(){
//        DefaultTreeModel model = (DefaultTreeModel) networkJTree.getModel();
//
//        
//        
//        ArrayList<Network> networkList = ecosystem.getNetworkList();
//        ArrayList<Enterprise> enterpriseList;
//        ArrayList<Organization> organizationList;
//        Network network;
//        Enterprise enterprise;
//        Organization organization;
//
//        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
//        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
//        root.removeAllChildren();
//        root.insert(networks, 0);
//
//        DefaultMutableTreeNode networkNode;
//        
//        DefaultMutableTreeNode enterpriseNode;
//        
//        DefaultMutableTreeNode organizationNode;
//        
//        for (int i = 0; i < networkList.size(); i++) 
//        {
//            network = networkList.get(i);
//            
//            networkNode = new DefaultMutableTreeNode(network.getNetworkname());
//            
//            networks.insert(networkNode, i);
//
//            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();
//
//            for (int j = 0; j < enterpriseList.size(); j++) 
//            {
//                enterprise = enterpriseList.get(j);
//                
//                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
//                
//                networkNode.insert(enterpriseNode, j);
//
//                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
//                
//                for (int k = 0; k < organizationList.size(); k++) 
//                {
//                    organization = organizationList.get(k);
//                    
//                    organizationNode = new DefaultMutableTreeNode(organization.getName());
//                    
//                    enterpriseNode.insert(organizationNode, k);
//                }
//            }
//        }
//
//        model.reload();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageEnterpriseAdministrator;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblSystemAdministrator;
    // End of variables declaration//GEN-END:variables
}
